services:
  steamCmd:
    image: cm2network/steamcmd
    container_name: Steam-CMD
    volumes:
      - ../../cs2:/home/steam/cs2
    working_dir: /home/steam/steamcmd
    command: >
      ./steamcmd.sh +force_install_dir /home/steam/cs2 +login anonymous +app_update 730 validate +quit
