services:
  steamCmd:
    image: cm2network/steamcmd
    container_name: Steam-CMD
    volumes:
      - ../server:/home/steam/server
    working_dir: /home/steam/steamcmd
    command: >
      ./steamcmd.sh +force_install_dir /home/steam/server +login anonymous +app_update 730 validate +quit
